### ISSUE TITLE
The LoEHash

### ISSUE THREAD

**Issue by Devwarlt** [Devwarlt/COSD#1]
**The LoEHash:** 

> **LoEHash** source code now is public.

**Comment by GhostMaree** [comment]
https://github.com/ossimc82/fabiano-swagger-of-doom/blob/master/wServer/networking/handlers/GuildRemovePacketHandler.cs#L29

var p = client.Manager.FindPlayer(packet.Name);
to
var p = packet.Name.ToString(); 
not tested
