### ISSUE TITLE
Ability Spammers

### ISSUE THREAD

**Issue by Deivixo** [Devwarlt/COSD#12]
Not really a bug/glich. Just wanted to say that some people find it funny to spam their spell/poison/other ability, to make server lag.
A potential fix would be to add cooldown to ALL abilities. Here's what I think:

Cloak-keep the same
Quiver -2.5 sec cooldown(for all quivers)
Spell - 4-6 second cooldown(for all spells)
Tome- 2-3 sec cooldown(for all tomes)
Helm - keep the same
Shield -2.5 sec colldown (for all shields)
Seal- 3-4 sec cooldown (for all )
Poison- 4-6 sec cooldown (all)
Skull - 2-3 sec cooldown (all)
Orb- 2-3 sec cooldown (all)
Prism - 2.5-3 sec cooldown (all)
Scepter - 2-3 sec cooldown (all)
Star - 3 sec cooldown (all)

Fell free to chose what time you want the cooldown to be, but I think theese should be pretty good.

**Comment by Devwarlt** [comment]
We are adding this cooldown system to avoid over spam of abilities and constantly lags caused by it. Its coming soon as update X part 2.
