### ISSUE TITLE
New bosses and Updates

### ISSUE THREAD

**Issue by sharathm2** [Devwarlt/COSD#15]
Hey guys it's your Developer Fade here.  Here are some Ideas I came up with for some New Bosses and events.  I hope you're ready for the new updates!  Dev and I are working very hard to get them out soon and we have a lot planned.  Here are the boss Ideas and Events:

Sun God: Extremely new Hard event that is about 5x harder than the forgotten king.

Candy God: Drops candies and once 25 are stacked up you can get a new Warrior Skin.  Boss is decently hard and will be in the new Dungeon Lollipop Land.

Drake God: Very hard new event, drops ultimate drake eggs which are new pets with 90 90 90 stats to start off(Very rare drop).

Guard of the King: New event in realm that drops Shatters along with Avatar.  The guard of the king is a event which is a bit harder then the avatar but drops new whites and better loot.

MORE TO COME!!! 👍 

_________________________________________________________________________________

_Devwarlt_ - Time to code new events!

_Bork_- Lord of death....

_Hallow_-New updates?? Yes lmao.

**Comment by Devwarlt** [comment]
Yes of course. I hope new challenge and nasty monsters for players battle against to make gameplay of LoE Realm better.

**Comment by Devwarlt** [comment]
Already at change log notes.
