### ISSUE TITLE
Different Levels of bosses

### ISSUE THREAD

**Issue by sharathm2** [Devwarlt/COSD#21]
Since we may add different types of loot we should add different levels of bosses:  The levels base the drops and how rare the drops are.  The levels also base the exp the bosses give.

Low lands and Beach enemies: Common Level

Midlands: Common Level

Godlands: Uncommon level

Snake pit, Abyss, Sprite, Udls, Bellas, Manors, Lab, Cland- Rare level

Shaitans, Davy, LoD, Ice Cave, Puppet, Ddocks- Epic Level

Shatters, Tomb, Crawling Depths, Ocean Trench, Woodland Labyrinth- Legendary Level

Ether, Wine Cellar -LoE Level

More to come

Credits:

-Fade

**Comment by TrueHallow** [comment]
Good idea fade if Dev adds the rarity enchantment why not one for gods
