### ISSUE TITLE
New WIZARD set ( IDEA )

### ISSUE THREAD

**Issue by Vexior** [Devwarlt/COSD#24]
Hello guys this is my new wizard set idea
First to say:
WHY WIZZY?!
Wizzy is a Unplayed class.
lets begin with the sprites
GOOOOOOOOOOOO
![staff of the bloody wizard](https://cloud.githubusercontent.com/assets/24353189/20861937/a6cee27c-b99d-11e6-9c79-949949f6ce00.png)
Name: Staff of the bloody Wizard
Tier:ST
Desc:BAH, this staff is full of Blood. did you dont will wash it?
Stats +55hp,mp
drops: 1/1300 Arcdemon Malphas ( Whitebag )
Dmg: 50 - 110
Shots: 3
RoF: 75%
Armoe broke
Hit more Projectiles
![spell of the blood wizzard](https://cloud.githubusercontent.com/assets/24353189/20861939/a952a86c-b99d-11e6-82e5-5c6f5e0d27d5.png)
Name: Spell of the bloody Wizard
Tier:ST
Desc:it will spear Blood?!  OH, GOD. PLS NO!!
Stats +5atk +10hp,mp
Drops: 1/2500 arcdemon malphas
dmg: 110 - 150
shots:20
Armor broke
Drops: 1/1500 Archdemon Malphas ( Whitebag )
![robe of the bloody wizard](https://cloud.githubusercontent.com/assets/24353189/20861973/96e05462-b99e-11e6-8eeb-4d7c78daad0b.png)
Robe of the bloody Wizard
Tier:ST
Desc:Did you Killed someone? YOU! MONSTER!!! 
Stats: +20def +1dex +2atk +40hp,mp
Drops: 1/1500 Archdemon Malphas ( whitebag )
![ring of the bloody wizard](https://cloud.githubusercontent.com/assets/24353189/20861941/ae6d0f04-b99d-11e6-9942-8b7a4a69cf39.png)
name: Ring of the Bloody Wizard
Desc:he blood is still Dropping is the ring fresh maded out of Blood?!
stats: 5+atk 5+dex 5+vit 5+wis +5def +5spd +35hp +35mp
Drops: 1/5000 Arcdemon malphas ( whitebag )
![shoot](https://cloud.githubusercontent.com/assets/24353189/20861942/b298e918-b99d-11e6-94d6-10d7f4e2f51b.png)
Shoot Wipeout set
![shoot with full set](https://cloud.githubusercontent.com/assets/24353189/20861943/b48f1a1c-b99d-11e6-8fca-576f57677b60.png)
Shoot with set
Ayyy Leaf a rate for my first Sprites in a 0/10 rateing pls thanks
btw set called "The bloody Wizard"

**Comment by Vexior** [comment]
Name: Spell of the bloody Wizard
Tier:ST
Desc:it will spear Blood?! OH, GOD. PLS NO!!
Stats +5atk +10hp,mp
Drops: 1/2500 arcdemon malphas
dmg: 90 - 150
shots:20
Armor broke
Drops: 1/3500 Archdemon Malphas ( Whitebag )
EDIT:// mabye it too OP for 1/1500 <:

**Comment by IncogSNeeko** [comment]
Horrible idea. This is too broken, causes server lag, and also is too bloody. The broken bit comes with the staff ARMOUR PIERCING AND HIT MORE PROJECTILE (piercing), DEALING 3 SHOTS AT 50-110 damage. Tell me how this is not broken. Then you have the spell which is the same as ST spell, which should be different. So all your damage is ARMOUR PIERCING. That is broken. Wizards also cause server lag, and spells are banned at the moment, so you can't even use the whole set.  And the ring is broken as well. There you go. Have fun if we do get this, because the server won't be as good.

**Comment by Vexior** [comment]
@PikaBoi hm. also when i play wizzy i dont have lags i still playing with 60fps
End.
