### ISSUE TITLE
Scammer Report Thread

### ISSUE THREAD

**Issue by TheKingOfTheInternet** [Devwarlt/COSD#27]
Decided to make a scammer report thread. Ill start with TurtleCool who scammed me of LT pyra and more. His alt is Turtlelove and his prod is alexg. Please either bann TurtleCool or IP bann him

**Comment by Devwarlt** [comment]
Wait our community moderators verify your request.

Cordially, Devwarlt.

**Comment by BorksGreatMemes** [comment]
FreshCo#3669 is a duper/scammer
his igns are Fresh and Kanye
