### ISSUE TITLE
How to exchange Fame For Gold

### ISSUE THREAD

**Issue by OmnipotentWaffleGod** [Devwarlt/COSD#30]
Well I want to see how to change my Fame To Gold because I was told i could do that. Sooo,yea It would be nice if someone could tell me.

**Comment by Devwarlt** [comment]
There is no exchange system yet to convert fame for gold. However, you can buy treasures from other players or atleast star ensigns (from donators).

**Comment by OmnipotentWaffleGod** [comment]
Ok,thanks for informing me.
