### ISSUE TITLE
Purple Bag GodLands glitch

### ISSUE THREAD

**Issue by sharathm2** [Devwarlt/COSD#4]
In GodLands, you can trade SB items through Purple bags.  This needs to be patched so SB items cannot be abused and traded without a DOTMG

**Comment by Devwarlt** [comment]
Alright thanks. What type of item its happening? Describe all items found at this moment.

**Comment by sharathm2** [comment]
Uhh, Well dev btw this is fade and this happens for all items.  I just
banned account for trading an lt fplate for a dbow in glands through
pbags.  Pbags in glands are public so people can drop items in it and
give/trade to other people.

**Comment by sharathm2** [comment]
also t7-t9 armors and weapons drop in glands. As well as t4 abilities.

**Comment by Deivixo** [comment]
And T4 rings, T3 abilities(I don't know about T3 rings though)

**Comment by Devwarlt** [comment]
Hmm... Basically all stuffs in god lands.

**Comment by sharathm2** [comment]
yea

**Comment by Devwarlt** [comment]
Going to check code of god lands loot.

**Comment by Devwarlt** [comment]
Bug has been solved. Thanks for participation.

**Comment by sharathm2** [comment]
NP
