### ISSUE TITLE
Character selection screen [Missing Button]

### ISSUE THREAD

**Issue by Deivixo** [Devwarlt/COSD#5]
Character selection screen is missing button "Back", so you cannot go to main screen from there.
![nobackbuttononcharacterselectionscreenbug](https://cloud.githubusercontent.com/assets/22724338/19221720/5c3b8386-8e51-11e6-8a70-a27ebe0911a7.png)

**Comment by Devwarlt** [comment]
Thanks for report, I'm going to patch it today yet.

**Comment by Devwarlt** [comment]
Patched on build 5.
