### ISSUE TITLE
Woodland Labyrinth overspawn

### ISSUE THREAD

**Issue by Deivixo** [Devwarlt/COSD#6]
Murderous Megamoth(last stage of boss) overspawns blue larvas(larvae?) 
![woodlandoverspawnbug](https://cloud.githubusercontent.com/assets/22724338/19221785/8910d644-8e52-11e6-872a-27bab1ae5092.png)

**Comment by Devwarlt** [comment]
Thanks, I will check it soon as possible.

**Comment by Devwarlt** [comment]
Patched.
