### ISSUE TITLE
nexus.Nexus [Text]

### ISSUE THREAD

**Issue by Deivixo** [Devwarlt/COSD#7]
When you nexus, it says "Connecting to nexus.Nexus" instead of normal "Connecting to Nexus"
![nexus nexusbug](https://cloud.githubusercontent.com/assets/22724338/19221906/1893e87c-8e55-11e6-9dd3-07996b8c2012.png)

**Comment by Devwarlt** [comment]
I wish its located at en.txt file of server directory. Really quick to patch, but I will look for it later. Thanks anyways.
