### ISSUE TITLE
Mini Skin dyes are mixed up. [Visual]

### ISSUE THREAD

**Issue by Deivixo** [Devwarlt/COSD#8]
These skins have mixed up big and small dyes.(If you use small dye, it colors more pixels than small and vice versa)
Mini Oryx (Knight)
Mini Twilight (Wizard)
Mini Phylactery (Mystic)
Mini Swoll (Paladin)
![minioryxdyebug](https://cloud.githubusercontent.com/assets/22724338/19221942/a5538862-8e55-11e6-9010-3888cfc292fa.png)
![minioryxdyebug2](https://cloud.githubusercontent.com/assets/22724338/19221948/c234f592-8e55-11e6-86f3-7934d1712609.png)

**Comment by Devwarlt** [comment]
Thank you @IAmlawa, it was patched on build 6.
